#include "stm32h7xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "config.h"
#include "uart_serial.h"
#include "tft_display.h"
#include "serial_task.h"
#include "keyboard_task.h"
#include "display_task.h"

extern UART_HandleTypeDef huart1;

QueueHandle_t screen_queue = NULL;
QueueHandle_t keyboard_queue = NULL;

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_FSMC_Init(void);  /* For TFT parallel interface */
static void MX_USB_HOST_Init(void);

int main(void) {
    /* HAL Initialization */
    HAL_Init();
    SystemClock_Config();
    
    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_USART1_UART_Init();
    MX_FSMC_Init();
    MX_USB_HOST_Init();
    
    /* Initialize UART driver */
    UART_Init(&huart1);
    
    /* Create queues */
    screen_queue = xQueueCreate(1, SCREEN_BUFFER_SIZE);
    keyboard_queue = xQueueCreate(8, sizeof(uint8_t));
    
    if (screen_queue == NULL || keyboard_queue == NULL) {
        /* Queue creation failed */
        while (1);
    }
    
    /* Create FreeRTOS tasks */
    xTaskCreate(SerialTask, "SerialTask", TASK_STACK_SIZE * 4, NULL, SERIAL_TASK_PRIO, NULL);
    xTaskCreate(KeyboardTask, "KeyboardTask", TASK_STACK_SIZE * 2, NULL, KEYBOARD_TASK_PRIO, NULL);
    xTaskCreate(DisplayTask, "DisplayTask", TASK_STACK_SIZE * 4, NULL, DISPLAY_TASK_PRIO, NULL);
    
    /* Start FreeRTOS scheduler */
    vTaskStartScheduler();
    
    /* Should never reach here */
    while (1);
    
    return 0;
}

void SystemClock_Config(void) {
    /* Configure system clock for STM32H7 - 400 MHz */
    /* This would be generated by STM32CubeMX */
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
    
    /* Initializes the RCC Oscillators according to the specified parameters */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 5;
    RCC_OscInitStruct.PLL.PLLN = 160;
    RCC_OscInitStruct.PLL.PLLP = 2;
    RCC_OscInitStruct.PLL.PLLQ = 4;
    
    HAL_RCC_OscConfig(&RCC_OscInitStruct);
    
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;
    
    HAL_RCC_ClkConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4);
}

static void MX_GPIO_Init(void) {
    /* GPIO Initialization */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();
    __HAL_RCC_GPIOE_CLK_ENABLE();
}

static void MX_USART1_UART_Init(void) {
    huart1.Instance = USART1;
    huart1.Init.BaudRate = UART_BAUD_RATE;
    huart1.Init.WordLength = UART_WORDLENGTH_8B;
    huart1.Init.StopBits = UART_STOPBITS_1;
    huart1.Init.Parity = UART_PARITY_NONE;
    huart1.Init.Mode = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    HAL_UART_Init(&huart1);
}

static void MX_FSMC_Init(void) {
    /* FSMC initialization for TFT parallel interface */
    /* Configure FSMC for 16-bit interface to TFT LCD */
    /* This would be generated by STM32CubeMX */
}

static void MX_USB_HOST_Init(void) {
    /* USB Host initialization for keyboard */
    /* This would be generated by STM32CubeMX USB Host configuration */
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    /* Stack overflow detected */
    while (1);
}

void vApplicationMallocFailedHook(void) {
    /* Memory allocation failed */
    while (1);
}
